# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sLDDuFcvklWwyx6XNjku-Hey6fX-UGmr
"""

import streamlit as st
import pandas as pd
import pickle

# --------------------------------------------------
# Page Configuration
# --------------------------------------------------
st.set_page_config(
    page_title="Delivery Time Estimator",
    page_icon="🚴",
    layout="centered"
)

st.title("🚴 Delivery Time Estimation App")
st.write("Enter delivery, order, and environment details to predict delivery time.")

# --------------------------------------------------
# Load Model & Preprocessor
# --------------------------------------------------
@st.cache_resource
def load_artifacts():
    with open("best_rf_model.pkl", "rb") as f:
        model = pickle.load(f)
    with open("preprocessor.pkl", "rb") as f:
        preprocessor = pickle.load(f)
    return model, preprocessor

model, preprocessor = load_artifacts()

# --------------------------------------------------
# User Input Form
# --------------------------------------------------
with st.form("delivery_form"):

    st.subheader("👤 Delivery Person Details")

    delivery_person_age = st.number_input(
        "Delivery Person Age",
        min_value=18,
        max_value=60,
        value=25
    )

    delivery_person_ratings = st.slider(
        "Delivery Person Rating",
        min_value=1.0,
        max_value=5.0,
        value=4.5,
        step=0.1
    )

    vehicle_condition = st.slider(
        "Vehicle Condition (1 = Poor, 10 = Excellent)",
        min_value=1,
        max_value=10,
        value=7
    )

    st.subheader("📦 Order Details")

    type_of_order = st.selectbox(
        "Type of Order",
        ["Snack", "Meal", "Drinks", "Buffet"]
    )

    type_of_vehicle = st.selectbox(
        "Type of Vehicle",
        ["Bike", "Scooter", "Car"]
    )

    st.subheader("📍 Location Details")

    restaurant_latitude = st.number_input(
        "Restaurant Latitude",
        format="%.6f",
        value=12.971600
    )

    restaurant_longitude = st.number_input(
        "Restaurant Longitude",
        format="%.6f",
        value=77.594600
    )

    delivery_location_latitude = st.number_input(
        "Delivery Latitude",
        format="%.6f",
        value=12.961100
    )

    delivery_location_longitude = st.number_input(
        "Delivery Longitude",
        format="%.6f",
        value=77.638700
    )

    st.subheader("🌦 Environment Details")

    weather_conditions = st.selectbox(
        "Weather Conditions",
        ["Sunny", "Cloudy", "Rainy", "Fog"]
    )

    road_traffic_density = st.selectbox(
        "Road Traffic Density",
        ["Low", "Medium", "High", "Jam"]
    )

    # Submit button
    submit = st.form_submit_button("🚀 Predict Delivery Time")

# --------------------------------------------------
# Prediction Logic
# --------------------------------------------------
if submit:

    input_df = pd.DataFrame([{
        "delivery_person_age": delivery_person_age,
        "delivery_person_ratings": delivery_person_ratings,
        "vehicle_condition": vehicle_condition,
        "type_of_order": type_of_order,
        "type_of_vehicle": type_of_vehicle,
        "restaurant_latitude": restaurant_latitude,
        "restaurant_longitude": restaurant_longitude,
        "delivery_location_latitude": delivery_location_latitude,
        "delivery_location_longitude": delivery_location_longitude,
        "weather_conditions": weather_conditions,
        "road_traffic_density": road_traffic_density
    }])

    processed_input = preprocessor.transform(input_df)
    prediction = model.predict(processed_input)[0]

    st.success(f"⏱ Estimated Delivery Time: **{round(prediction, 2)} minutes**")

    with st.expander("🔍 View Entered Input Values"):
        st.dataframe(input_df)