# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dvGfrWE_wnw8Sl6kCZCrlxA40Vty5jyY
"""

import streamlit as st
import pandas as pd
import datetime

st.set_page_config(page_title="Delivery Time Estimator", layout="centered")

st.title("🚴 Delivery Time Estimation App")

# ---------------------------
# User Inputs
# ---------------------------

# Delivery Person Info
delivery_person_age = st.number_input(
    "Delivery Person Age", min_value=18, max_value=60, value=25, key="delivery_person_age"
)

delivery_person_ratings = st.number_input(
    "Delivery Person Ratings", min_value=1.0, max_value=5.0, value=4.5, step=0.1, key="delivery_person_ratings"
)

vehicle_condition = st.selectbox(
    "Vehicle Condition",
    options=["Excellent", "Good", "Average", "Poor"],
    key="vehicle_condition"
)

type_of_vehicle = st.selectbox(
    "Type of Vehicle",
    options=["Bike", "Scooter", "Car", "Truck"],
    key="type_of_vehicle"
)

# Restaurant & Delivery Location
restaurant_latitude = st.number_input(
    "Restaurant Latitude", value=12.9716, key="restaurant_latitude"
)
restaurant_longitude = st.number_input(
    "Restaurant Longitude", value=77.5946, key="restaurant_longitude"
)
delivery_latitude = st.number_input(
    "Delivery Location Latitude", value=12.9352, key="delivery_latitude"
)
delivery_longitude = st.number_input(
    "Delivery Location Longitude", value=77.6245, key="delivery_longitude"
)

# Order Info
order_date = st.date_input(
    "Order Date", datetime.date.today(), key="order_date"
)
time_ordered = st.time_input(
    "Time Ordered", datetime.datetime.now().time(), key="time_ordered"
)
time_order_picked = st.time_input(
    "Time Order Picked", datetime.datetime.now().time(), key="time_order_picked"
)

type_of_order = st.selectbox(
    "Type of Order",
    options=["Food", "Grocery", "Other"],
    key="type_of_order"
)

# Environment Info
weather_conditions = st.selectbox(
    "Weather Conditions",
    options=["Sunny", "Rainy", "Stormy", "Foggy", "Snowy", "Windy"],
    key="weather_conditions"
)

road_traffic_density = st.selectbox(
    "Road Traffic Density",
    options=["Low", "Medium", "High", "Jam"],
    key="road_traffic_density"
)

# ---------------------------
# Submit Button
# ---------------------------
if st.button("Predict Delivery Time", key="predict_button"):
    # Example: Calculate dummy delivery time
    import random
    estimated_time = random.randint(20, 60)  # placeholder for ML model
    st.success(f"Estimated Delivery Time: {estimated_time} minutes")

    # Optional: Show all inputs for verification
    st.subheader("Input Summary")
    input_data = {
        "Delivery Person Age": delivery_person_age,
        "Delivery Person Ratings": delivery_person_ratings,
        "Vehicle Condition": vehicle_condition,
        "Type of Vehicle": type_of_vehicle,
        "Restaurant Latitude": restaurant_latitude,
        "Restaurant Longitude": restaurant_longitude,
        "Delivery Latitude": delivery_latitude,
        "Delivery Longitude": delivery_longitude,
        "Order Date": order_date,
        "Time Ordered": time_ordered,
        "Time Order Picked": time_order_picked,
        "Type of Order": type_of_order,
        "Weather Conditions": weather_conditions,
        "Road Traffic Density": road_traffic_density
    }
    st.table(pd.DataFrame([input_data]))
