# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dvGfrWE_wnw8Sl6kCZCrlxA40Vty5jyY
"""

import streamlit as st
import pandas as pd
import pickle
import numpy as np

# Load trained model
with open('best_rf_model.pkl', 'rb') as f:
    model = pickle.load(f)

st.title("Zomato Delivery Time Prediction 🚀")

st.write("Enter the order details to predict delivery time:")

# ----------------------------
# User inputs
# ----------------------------
# Numeric inputs
delivery_person_age = st.number_input("Delivery Person Age", min_value=18, max_value=60, value=25)
delivery_person_ratings = st.number_input("Delivery Person Ratings", min_value=1.0, max_value=5.0, value=4.5)
distance_km = st.number_input("Distance (km)", min_value=0.1, max_value=50.0, value=5.0)

# Categorical inputs
weather_conditions = st.selectbox("Weather Conditions", ["Sunny", "Rainy", "Stormy", "Cloudy"])
road_traffic_density = st.selectbox("Road Traffic Density", ["Low", "Medium", "High", "Jam"])
type_of_order = st.selectbox("Type of Order", ["Snack", "Meal", "Drinks"])
type_of_vehicle = st.selectbox("Type of Vehicle", ["Bike", "Scooter", "Car"])
festival = st.selectbox("Festival", ["Yes", "No"])
city = st.selectbox("City", ["Metropolitan", "Urban", "Semi-Urban"])
peak_hours = st.selectbox("Peak Hours?", [0, 1])

# ----------------------------
# Make prediction
# ----------------------------
if st.button("Predict Delivery Time ⏱️"):
    # Create a single-row dataframe
    input_df = pd.DataFrame({
        'delivery_person_age': [delivery_person_age],
        'delivery_person_ratings': [delivery_person_ratings],
        'distance_km': [distance_km],
        'weather_conditions': [weather_conditions],
        'road_traffic_density': [road_traffic_density],
        'type_of_order': [type_of_order],
        'type_of_vehicle': [type_of_vehicle],
        'festival': [festival],
        'city': [city],
        'peak_hours': [peak_hours]
    })

    # Encode categoricals (same as training)
    input_encoded = pd.get_dummies(input_df)
    # Align with training columns
    missing_cols = set(model.feature_names_in_) - set(input_encoded.columns)
    for col in missing_cols:
        input_encoded[col] = 0
    input_encoded = input_encoded[model.feature_names_in_]

    # Predict
    prediction = model.predict(input_encoded)[0]
    st.success(f"Estimated Delivery Time: {prediction:.2f} minutes")
import streamlit as st
import pandas as pd
import pickle
import numpy as np

# Load trained model
with open('best_rf_model.pkl', 'rb') as f:
    model = pickle.load(f)

st.title("Zomato Delivery Time Prediction 🚀")

st.write("Enter the order details to predict delivery time:")

# ----------------------------
# User inputs
# ----------------------------
# Numeric inputs
delivery_person_age = st.number_input("Delivery Person Age", min_value=18, max_value=60, value=25)
delivery_person_ratings = st.number_input("Delivery Person Ratings", min_value=1.0, max_value=5.0, value=4.5)
distance_km = st.number_input("Distance (km)", min_value=0.1, max_value=50.0, value=5.0)

# Categorical inputs
weather_conditions = st.selectbox("Weather Conditions", ["Sunny", "Rainy", "Stormy", "Cloudy"])
road_traffic_density = st.selectbox("Road Traffic Density", ["Low", "Medium", "High", "Jam"])
type_of_order = st.selectbox("Type of Order", ["Snack", "Meal", "Drinks"])
type_of_vehicle = st.selectbox("Type of Vehicle", ["Bike", "Scooter", "Car"])
festival = st.selectbox("Festival", ["Yes", "No"])
city = st.selectbox("City", ["Metropolitan", "Urban", "Semi-Urban"])
peak_hours = st.selectbox("Peak Hours?", [0, 1])

# ----------------------------
# Make prediction
# ----------------------------
if st.button("Predict Delivery Time ⏱️"):
    # Create a single-row dataframe
    input_df = pd.DataFrame({
        'delivery_person_age': [delivery_person_age],
        'delivery_person_ratings': [delivery_person_ratings],
        'distance_km': [distance_km],
        'weather_conditions': [weather_conditions],
        'road_traffic_density': [road_traffic_density],
        'type_of_order': [type_of_order],
        'type_of_vehicle': [type_of_vehicle],
        'festival': [festival],
        'city': [city],
        'peak_hours': [peak_hours]
    })

    # Encode categoricals (same as training)
    input_encoded = pd.get_dummies(input_df)
    # Align with training columns
    missing_cols = set(model.feature_names_in_) - set(input_encoded.columns)
    for col in missing_cols:
        input_encoded[col] = 0
    input_encoded = input_encoded[model.feature_names_in_]

    # Predict
    prediction = model.predict(input_encoded)[0]
    st.success(f"Estimated Delivery Time: {prediction:.2f} minutes")